// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20231117160536_changeBaseVerbsToVerbs")]
    partial class changeBaseVerbsToVerbs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.PersistenceEntities.NounEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NounArticle")
                        .HasColumnType("int");

                    b.Property<int>("NounDeclension")
                        .HasColumnType("int");

                    b.Property<string>("PluralForm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SingularForm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nouns");
                });

            modelBuilder.Entity("Data.PersistenceEntities.Verbs.Shared.BaseVerb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Imperative")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentTense")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerbConjugation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("verb_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Verbs");

                    b.HasDiscriminator<string>("verb_type").HasValue("BaseVerb");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Data.PersistenceEntities.Verbs.IrregularVerb", b =>
                {
                    b.HasBaseType("Data.PersistenceEntities.Verbs.Shared.BaseVerb");

                    b.Property<string>("Infinitive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PastTense")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Verbs");

                    b.HasDiscriminator().HasValue("Irregular");
                });

            modelBuilder.Entity("Data.PersistenceEntities.Verbs.ShortVerb", b =>
                {
                    b.HasBaseType("Data.PersistenceEntities.Verbs.Shared.BaseVerb");

                    b.ToTable("Verbs");

                    b.HasDiscriminator().HasValue("Short");
                });

            modelBuilder.Entity("Data.PersistenceEntities.Verbs.StrongVerb", b =>
                {
                    b.HasBaseType("Data.PersistenceEntities.Verbs.Shared.BaseVerb");

                    b.Property<int>("VowelChangeGroup")
                        .HasColumnType("int");

                    b.ToTable("Verbs");

                    b.HasDiscriminator().HasValue("Strong");
                });

            modelBuilder.Entity("Data.PersistenceEntities.Verbs.WeakVerb", b =>
                {
                    b.HasBaseType("Data.PersistenceEntities.Verbs.Shared.BaseVerb");

                    b.ToTable("Verbs");

                    b.HasDiscriminator().HasValue("Weak");
                });
#pragma warning restore 612, 618
        }
    }
}
