// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(SqlContext))]
    partial class SqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.PersistenceEntities.NounEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nchar(36)")
                        .IsFixedLength();

                    b.Property<string>("GrammaticalGender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NounArticle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NounDeclension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PluralForm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SingularForm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GrammaticalGender");

                    b.HasIndex("NounDeclension");

                    b.HasIndex("SingularForm");

                    b.HasIndex("SingularForm", "PluralForm")
                        .IsUnique();

                    b.ToTable("Nouns", null, t =>
                        {
                            t.HasCheckConstraint("CK_Nouns_PluralForm_NotEmpty", "LEN([PluralForm]) > 0");

                            t.HasCheckConstraint("CK_Nouns_SingularForm_NotEmpty", "LEN([SingularForm]) > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = "b73f8789-958b-4752-9f70-6d1a73794b03",
                            GrammaticalGender = "Masculine",
                            NounArticle = "en",
                            NounDeclension = "Two",
                            PluralForm = "pojkar",
                            SingularForm = "pojke"
                        },
                        new
                        {
                            Id = "a163d3d1-70c1-4dbf-872c-8ebad193d3ef",
                            GrammaticalGender = "Feminine",
                            NounArticle = "en",
                            NounDeclension = "One",
                            PluralForm = "flickor",
                            SingularForm = "flicka"
                        },
                        new
                        {
                            Id = "cca1e103-c140-4acf-a7bf-32b14adab539",
                            GrammaticalGender = "CommonGender",
                            NounArticle = "en",
                            NounDeclension = "Two",
                            PluralForm = "bilar",
                            SingularForm = "bil"
                        },
                        new
                        {
                            Id = "7357f66f-f38e-4f15-b949-3caa228d0b1f",
                            GrammaticalGender = "CommonGender",
                            NounArticle = "en",
                            NounDeclension = "Two",
                            PluralForm = "fiskar",
                            SingularForm = "fisk"
                        },
                        new
                        {
                            Id = "d42ae057-05ce-4f93-9b17-75d2689c06e7",
                            GrammaticalGender = "CommonGender",
                            NounArticle = "en",
                            NounDeclension = "Two",
                            PluralForm = "böcker",
                            SingularForm = "bok"
                        },
                        new
                        {
                            Id = "9e1c3f4a-8f4e-4d2a-9f3e-2b6c5d7e8f9a",
                            GrammaticalGender = "CommonGender",
                            NounArticle = "en",
                            NounDeclension = "Three",
                            PluralForm = "städer",
                            SingularForm = "stad"
                        },
                        new
                        {
                            Id = "f38485c6-be45-4d52-a043-a561ff09467d",
                            GrammaticalGender = "Neuter",
                            NounArticle = "ett",
                            NounDeclension = "Four",
                            PluralForm = "hus",
                            SingularForm = "hus"
                        },
                        new
                        {
                            Id = "8a9bb56c-2604-4ae6-8462-f044fa5239dc",
                            GrammaticalGender = "Neuter",
                            NounArticle = "ett",
                            NounDeclension = "Five",
                            PluralForm = "brev",
                            SingularForm = "brev"
                        });
                });

            modelBuilder.Entity("Data.PersistenceEntities.VerbEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nchar(36)")
                        .IsFixedLength();

                    b.Property<string>("Imperative")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Infinitive")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PastTense")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PresentTense")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Supine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VerbConjugation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Infinitive");

                    b.ToTable("Verbs", null, t =>
                        {
                            t.HasCheckConstraint("CK_Verbs_Imperative_NotEmpty", "LEN([Infinitive]) > 0");

                            t.HasCheckConstraint("CK_Verbs_Infinitive_NotEmpty", "LEN([Infinitive]) > 0");

                            t.HasCheckConstraint("CK_Verbs_PastTense_NotEmpty", "LEN([Infinitive]) > 0");

                            t.HasCheckConstraint("CK_Verbs_PresentTense_NotEmpty", "LEN([PresentTense]) > 0");

                            t.HasCheckConstraint("CK_Verbs_Supine_NotEmpty", "LEN([Infinitive]) > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = "8e87ea09-a6bf-431c-9559-b5221b14e81b",
                            Imperative = "ha",
                            Infinitive = "ha",
                            PastTense = "hade",
                            PresentTense = "har",
                            Supine = "haft",
                            VerbConjugation = "Irregular"
                        },
                        new
                        {
                            Id = "3c9d5f4e-2b6a-4f8e-9c3d-1e2f3a4b5c6d",
                            Imperative = "——EJ TILLÄMPBAR——",
                            Infinitive = "skola",
                            PastTense = "skulle",
                            PresentTense = "ska",
                            Supine = "skolat",
                            VerbConjugation = "Irregular"
                        },
                        new
                        {
                            Id = "8b0e7e1a-13fb-45b3-9667-ebfbb938e6c6",
                            Imperative = "prata",
                            Infinitive = "prata",
                            PastTense = "pratade",
                            PresentTense = "pratar",
                            Supine = "pratat",
                            VerbConjugation = "WeakOne"
                        },
                        new
                        {
                            Id = "abcdef12-3456-7890-abcd-ef1234567890",
                            Imperative = "läs",
                            Infinitive = "läsa",
                            PastTense = "läste",
                            PresentTense = "läser",
                            Supine = "läst",
                            VerbConjugation = "WeakTwo"
                        },
                        new
                        {
                            Id = "a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d",
                            Imperative = "bo",
                            Infinitive = "bo",
                            PastTense = "bodde",
                            PresentTense = "bor",
                            Supine = "bott",
                            VerbConjugation = "WeakThree"
                        },
                        new
                        {
                            Id = "f4e5d6c7-b8a9-0b1c-2d3e-4f5a6b7c8d9e",
                            Imperative = "spring",
                            Infinitive = "springa",
                            PastTense = "sprang",
                            PresentTense = "springer",
                            Supine = "sprungit",
                            VerbConjugation = "StrongFour"
                        },
                        new
                        {
                            Id = "12345678-90ab-cdef-1234-567890abcdef",
                            Imperative = "skriv",
                            Infinitive = "skriva",
                            PastTense = "skrev",
                            PresentTense = "skriver",
                            Supine = "skrivit",
                            VerbConjugation = "StrongFour"
                        },
                        new
                        {
                            Id = "9abcdef0-1234-5678-9abc-def012345678",
                            Imperative = "ljug",
                            Infinitive = "ljuga",
                            PastTense = "ljög",
                            PresentTense = "ljuger",
                            Supine = "ljugit",
                            VerbConjugation = "StrongFour"
                        },
                        new
                        {
                            Id = "23456789-0abc-def1-2345-67890abcdef1",
                            Imperative = "flyg",
                            Infinitive = "flyga",
                            PastTense = "flög",
                            PresentTense = "flyger",
                            Supine = "flugit",
                            VerbConjugation = "StrongFour"
                        },
                        new
                        {
                            Id = "8217bd0f-d1df-4660-b07b-063c33d7f559",
                            Imperative = "ta",
                            Infinitive = "ta",
                            PastTense = "tog",
                            PresentTense = "tar",
                            Supine = "tagit",
                            VerbConjugation = "StrongFour"
                        },
                        new
                        {
                            Id = "34567890-1bcd-ef23-4567-890abcdef123",
                            Imperative = "bär",
                            Infinitive = "bära",
                            PastTense = "bar",
                            PresentTense = "bär",
                            Supine = "burit",
                            VerbConjugation = "StrongFour"
                        },
                        new
                        {
                            Id = "45678901-2cde-f345-6789-0abcdef12345",
                            Imperative = "gråt",
                            Infinitive = "gråta",
                            PastTense = "grät",
                            PresentTense = "gråter",
                            Supine = "gråtit",
                            VerbConjugation = "StrongFour"
                        },
                        new
                        {
                            Id = "d3f5c4e2-2c4b-4f3a-9f3e-2e5f6c7d8e9f",
                            Imperative = "ät",
                            Infinitive = "äta",
                            PastTense = "åt",
                            PresentTense = "äter",
                            Supine = "ätit",
                            VerbConjugation = "StrongFour"
                        },
                        new
                        {
                            Id = "5713f1ff-9e9e-40c7-901c-ba992a91608e",
                            Imperative = "håll",
                            Infinitive = "hålla",
                            PastTense = "höll",
                            PresentTense = "håller",
                            Supine = "hållit",
                            VerbConjugation = "StrongFour"
                        },
                        new
                        {
                            Id = "56789012-3def-4567-890a-bcdef1234567",
                            Imperative = "drick",
                            Infinitive = "dricka",
                            PastTense = "drack",
                            PresentTense = "dricker",
                            Supine = "druckit",
                            VerbConjugation = "StrongFour"
                        },
                        new
                        {
                            Id = "346bcffa-9f2c-498c-8c5a-0394293b4e4e",
                            Imperative = "ge",
                            Infinitive = "ge",
                            PastTense = "gav",
                            PresentTense = "ger",
                            Supine = "gett",
                            VerbConjugation = "StrongFour"
                        },
                        new
                        {
                            Id = "67890123-4ef5-6789-0abc-def123456789",
                            Imperative = "kom",
                            Infinitive = "komma",
                            PastTense = "kom",
                            PresentTense = "kommer",
                            Supine = "kommit",
                            VerbConjugation = "StrongFour"
                        },
                        new
                        {
                            Id = "fedcba98-7654-3210-fedc-ba9876543210",
                            Imperative = "sov",
                            Infinitive = "sova",
                            PastTense = "sov",
                            PresentTense = "sover",
                            Supine = "sovit",
                            VerbConjugation = "StrongFour"
                        },
                        new
                        {
                            Id = "78901234-5f67-890a-bcde-f1234567890a",
                            Imperative = "var",
                            Infinitive = "vara",
                            PastTense = "var",
                            PresentTense = "är",
                            Supine = "varit",
                            VerbConjugation = "Irregular"
                        },
                        new
                        {
                            Id = "0fedcba9-8765-4321-0fed-cba987654321",
                            Imperative = "få",
                            Infinitive = "få",
                            PastTense = "fick",
                            PresentTense = "får",
                            Supine = "fått",
                            VerbConjugation = "Irregular"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
